### ISSUE TITLE
大佬，我们学校也是深澜，情况和你们差不多，我想问下怎么把算法搞到路由上呢？没有怎么玩过路由

### ISSUE THREAD

**Issue by AlwaysLazy21** [logan996007/NCHU-Srun-3K-PPPOE#1]
或者你可以给我推荐几篇文章什么的，让我自己去看，感谢！已经**star**

**Comment by logan996007** [comment]
我们学校的宽带账号是静态加密，你可以参考一下下面的那段代码，大意是获取加密后的宽带账号前缀（后缀可能是你们的学校相关的，例如@XXXu.edu），然后把加密后的账号，填入路由器拨号的账号当中即可拨号。后缀的获取包括账号的获取还有一种方式，使用ethreal抓包软件，在正常拨号时进行抓包，也可以抓到加密后的账号，观察加密后的账号即可看出后缀；也可以多拨号抓包几次观察账号会不会改变，如果不改变则是静态加密，可直接填入路由器拨号。希望可以帮助到你
def getName(username):
    username_crypto = ""
    for i in range(len(username)):
        username_crypto += chr(ord(username[i])+4)

    return "{SRUN2}" + username_crypto+'@stu.nchu.edu.cn'

**Comment by AlwaysLazy21** [comment]
我们学校是网页端认证，然后我通过多次抓包，分析post的参数，看看是什么加密，静态加密的话，就把账号的明文直接填入路由，进行拨号。是这样吗？不用刷固件？不用改mac?

**Comment by logan996007** [comment]
只有pppoe拨号才能使用照搬我的方法，但加密方法可能是一样的，多试试

**Comment by AlwaysLazy21** [comment]
ok




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月6日(星期二) 中午11:35
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [logan996007/NCHU-Srun-3K-PPPOE] 大佬，我们学校也是深澜，情况和你们差不多，我想问下怎么把算法搞到路由上呢？没有怎么玩过路由 (Issue #1)





 
只有pppoe拨号才能使用照搬我的方法，但加密方法可能是一样的，多试试
